/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CChatIdRouteImport } from './routes/c.$chatId'
import { Route as ApiOpencodeRouteImport } from './routes/api/opencode'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CChatIdRoute = CChatIdRouteImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpencodeRoute = ApiOpencodeRouteImport.update({
  id: '/api/opencode',
  path: '/api/opencode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/api/opencode': typeof ApiOpencodeRoute
  '/c/$chatId': typeof CChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/api/opencode': typeof ApiOpencodeRoute
  '/c/$chatId': typeof CChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/api/opencode': typeof ApiOpencodeRoute
  '/c/$chatId': typeof CChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library' | '/settings' | '/api/opencode' | '/c/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/settings' | '/api/opencode' | '/c/$chatId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/settings'
    | '/api/opencode'
    | '/c/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  ApiOpencodeRoute: typeof ApiOpencodeRoute
  CChatIdRoute: typeof CChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opencode': {
      id: '/api/opencode'
      path: '/api/opencode'
      fullPath: '/api/opencode'
      preLoaderRoute: typeof ApiOpencodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  ApiOpencodeRoute: ApiOpencodeRoute,
  CChatIdRoute: CChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
